# Dodajemy definicję usługi dla Minio do render.yaml
services:
  # Usługa dla backend API
  - type: web
    name: backend-api
    env: production
    buildCommand: |
      docker build -t miejscakultury.
    startCommand: |
      docker run -d -p 5000:5000 -p 5001:5001 miejscakultury
    envVars:
      - key=ConnectionStrings__Default
        value=Host=db;Port=5432;Database=miejscakultury;Username=postgres;Password=postgres
      - key=ASPNETCORE_ENVIRONMENT
        value=Production
      - key=ASPNETCORE_HTTP_PORTS
        value=5000
      - key=ASPNETCORE_HTTPS_PORTS
        value=5001
    volumes:
      -./path/to/your/project:/app
    resources:
      cpu: 1
      memory: 1024

  # Usługa dla Minio
  - type: web
    name: minio-storage
    env: production
    buildCommand: |
      docker pull minio/minio:latest
    startCommand: |
      docker run -d -p 9000:9000 -p 9001:9001 \
        -e MINIO_ROOT_USER=minioadmin \
        -e MINIO_ROOT_PASSWORD=minioadmin123 \
        -v minio_data:/data \
        minio/minio:latest server --console-address ":9001" --address ":9000" /data
    volumes:
      - minio_data:
          hostPath: /mnt/data
    resources:
      cpu: 0.5
      memory: 512
